/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cafe_Management_Systems;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author Mohammad Mahmudul Hasan
 */
public class Cafe_Management_System extends javax.swing.JFrame {

    double [] drink = new double[5];
    double [] cake = new double[8];
    String [] cost = new String[3];
    double [] i = new double[13];
    
    /**
     * Creates new form Cafe_Management_System
     */
    public Cafe_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jChkLattle = new javax.swing.JCheckBox();
        jChkIcedLattle = new javax.swing.JCheckBox();
        jChkEspresso = new javax.swing.JCheckBox();
        jChkCappuccino = new javax.swing.JCheckBox();
        jChkIcedCappuccino = new javax.swing.JCheckBox();
        jtxtLattle = new javax.swing.JTextField();
        jtxtIcedLattle = new javax.swing.JTextField();
        jtxtEspresso = new javax.swing.JTextField();
        jtxtCappuccino = new javax.swing.JTextField();
        jtxtIcedCappuccino = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jChkCoffeeCake = new javax.swing.JCheckBox();
        jChkRedVelvet = new javax.swing.JCheckBox();
        jChkBoston = new javax.swing.JCheckBox();
        jChkBlack = new javax.swing.JCheckBox();
        jChkKilburn = new javax.swing.JCheckBox();
        jChkLagos = new javax.swing.JCheckBox();
        jChkCarlton = new javax.swing.JCheckBox();
        jChkQueens = new javax.swing.JCheckBox();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtRedVelvet = new javax.swing.JTextField();
        jtxtBlack = new javax.swing.JTextField();
        jtxtBoston = new javax.swing.JTextField();
        jtxtLagos = new javax.swing.JTextField();
        jtxtKilburn = new javax.swing.JTextField();
        jtxtCarlton = new javax.swing.JTextField();
        jtxtQueens = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblTax = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JTextField();
        jlblSubTotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblCostCake = new javax.swing.JTextField();
        jlblCostDrinks = new javax.swing.JTextField();
        jlblService = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnTotal)
                .addGap(33, 33, 33)
                .addComponent(jBtnReceipt)
                .addGap(18, 18, 18)
                .addComponent(jBtnReset)
                .addGap(18, 18, 18)
                .addComponent(jBtnExit)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTotal)
                    .addComponent(jBtnReceipt)
                    .addComponent(jBtnReset)
                    .addComponent(jBtnExit))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, 440, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Hasan's Cafe IUB");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel1)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 1270, 100));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkLattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkLattle.setText("Lattle");
        jChkLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLattleMouseClicked(evt);
            }
        });
        jChkLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLattleActionPerformed(evt);
            }
        });

        jChkIcedLattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIcedLattle.setText("Iced Lattle");
        jChkIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedLattleMouseClicked(evt);
            }
        });

        jChkEspresso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkEspresso.setText("Espresso");
        jChkEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkEspressoMouseClicked(evt);
            }
        });

        jChkCappuccino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCappuccino.setText("Cappuccino");
        jChkCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCappuccinoMouseClicked(evt);
            }
        });
        jChkCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCappuccinoActionPerformed(evt);
            }
        });

        jChkIcedCappuccino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIcedCappuccino.setText("Iced Cappuccino");
        jChkIcedCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedCappuccinoMouseClicked(evt);
            }
        });
        jChkIcedCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIcedCappuccinoActionPerformed(evt);
            }
        });

        jtxtLattle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLattle.setText("0");
        jtxtLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLattleMouseClicked(evt);
            }
        });

        jtxtIcedLattle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtIcedLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedLattle.setText("0");
        jtxtIcedLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIcedLattleMouseClicked(evt);
            }
        });
        jtxtIcedLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIcedLattleActionPerformed(evt);
            }
        });

        jtxtEspresso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtEspresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEspresso.setText("0");
        jtxtEspresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEspressoMouseClicked(evt);
            }
        });
        jtxtEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEspressoActionPerformed(evt);
            }
        });

        jtxtCappuccino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCappuccino.setText("0");
        jtxtCappuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCappuccinoMouseClicked(evt);
            }
        });
        jtxtCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCappuccinoActionPerformed(evt);
            }
        });

        jtxtIcedCappuccino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtIcedCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedCappuccino.setText("0");
        jtxtIcedCappuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtIcedCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIcedCappuccinoMouseClicked(evt);
            }
        });
        jtxtIcedCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIcedCappuccinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkLattle)
                    .addComponent(jChkEspresso)
                    .addComponent(jChkIcedLattle)
                    .addComponent(jChkCappuccino)
                    .addComponent(jChkIcedCappuccino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIcedCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkLattle)
                    .addComponent(jtxtLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkIcedLattle))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkEspresso))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkCappuccino))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkIcedCappuccino)
                    .addComponent(jtxtIcedCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 320, 330));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkCoffeeCake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCoffeeCake.setText("Coffee Cake");
        jChkCoffeeCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCoffeeCakeMouseClicked(evt);
            }
        });

        jChkRedVelvet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkRedVelvet.setText("Red Velvet Cake");
        jChkRedVelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkRedVelvetMouseClicked(evt);
            }
        });

        jChkBoston.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkBoston.setText("Boston Cream Pie");
        jChkBoston.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBostonMouseClicked(evt);
            }
        });

        jChkBlack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkBlack.setText("Black Forest Cake");
        jChkBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBlackMouseClicked(evt);
            }
        });
        jChkBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBlackActionPerformed(evt);
            }
        });

        jChkKilburn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkKilburn.setText("Killburn Chocolate Cake");
        jChkKilburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkKilburnMouseClicked(evt);
            }
        });
        jChkKilburn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkKilburnActionPerformed(evt);
            }
        });

        jChkLagos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkLagos.setText("Lagos Chocolate Cake");
        jChkLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLagosMouseClicked(evt);
            }
        });
        jChkLagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLagosActionPerformed(evt);
            }
        });

        jChkCarlton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCarlton.setText("Carlton Hill Chocolate Cake");
        jChkCarlton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCarltonMouseClicked(evt);
            }
        });
        jChkCarlton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCarltonActionPerformed(evt);
            }
        });

        jChkQueens.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkQueens.setText("Queen's Park Chocolate Cake");
        jChkQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkQueensMouseClicked(evt);
            }
        });
        jChkQueens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkQueensActionPerformed(evt);
            }
        });

        jtxtCoffee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCoffeeMouseClicked(evt);
            }
        });
        jtxtCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCoffeeActionPerformed(evt);
            }
        });

        jtxtRedVelvet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtRedVelvet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRedVelvet.setText("0");
        jtxtRedVelvet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtRedVelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtRedVelvetMouseClicked(evt);
            }
        });
        jtxtRedVelvet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRedVelvetActionPerformed(evt);
            }
        });

        jtxtBlack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBlack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBlack.setText("0");
        jtxtBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBlackMouseClicked(evt);
            }
        });
        jtxtBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBlackActionPerformed(evt);
            }
        });

        jtxtBoston.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBoston.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBoston.setText("0");
        jtxtBoston.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtBoston.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBostonMouseClicked(evt);
            }
        });
        jtxtBoston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBostonActionPerformed(evt);
            }
        });

        jtxtLagos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtLagos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLagos.setText("0");
        jtxtLagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLagosMouseClicked(evt);
            }
        });
        jtxtLagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLagosActionPerformed(evt);
            }
        });

        jtxtKilburn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtKilburn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtKilburn.setText("0");
        jtxtKilburn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtKilburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKilburnMouseClicked(evt);
            }
        });
        jtxtKilburn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtKilburnActionPerformed(evt);
            }
        });

        jtxtCarlton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCarlton.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCarlton.setText("0");
        jtxtCarlton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCarlton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCarltonMouseClicked(evt);
            }
        });
        jtxtCarlton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCarltonActionPerformed(evt);
            }
        });

        jtxtQueens.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtQueens.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtQueens.setText("0");
        jtxtQueens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtQueensMouseClicked(evt);
            }
        });
        jtxtQueens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQueensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jChkCarlton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChkRedVelvet)
                                    .addComponent(jChkBoston)
                                    .addComponent(jChkBlack)
                                    .addComponent(jChkLagos)
                                    .addComponent(jChkKilburn)
                                    .addComponent(jChkCoffeeCake))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jChkQueens)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jtxtQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtKilburn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtLagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtBlack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtBoston, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtRedVelvet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(166, 166, 166))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkCoffeeCake)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jChkRedVelvet)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRedVelvet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBoston)
                    .addComponent(jtxtBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkBlack)
                    .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jChkLagos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkKilburn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkCarlton))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkQueens))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 480, 350));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tax");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Sub Total");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total");

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTax.setText("0");
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTotal.setText("0");
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlblTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblTotalActionPerformed(evt);
            }
        });

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblSubTotal.setText("0");
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlblSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblSubTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlblTotal)
                    .addComponent(jlblTax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 370, 170));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 440, 410));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cost of Drinks");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cost of Cakes");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Service Charge");

        jlblCostCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblCostCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblCostCake.setText("0");
        jlblCostCake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlblCostCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblCostCakeActionPerformed(evt);
            }
        });

        jlblCostDrinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblCostDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblCostDrinks.setText("0");
        jlblCostDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlblCostDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblCostDrinksActionPerformed(evt);
            }
        });

        jlblService.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblService.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblService.setText("5");
        jlblService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlblService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlblCostDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jlblCostCake)
                    .addComponent(jlblService))
                .addGap(28, 28, 28))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCostCake, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 430, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlblCostCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblCostCakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostCakeActionPerformed

    private void jlblServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblServiceActionPerformed

    private void jlblCostDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblCostDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostDrinksActionPerformed

    private void jChkKilburnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkKilburnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkKilburnActionPerformed

    private void jChkBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBlackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkBlackActionPerformed

    private void jChkLagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkLagosActionPerformed

    private void jChkCarltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCarltonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkCarltonActionPerformed

    private void jChkQueensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkQueensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkQueensActionPerformed

    private void jChkCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCappuccinoActionPerformed
      
    }//GEN-LAST:event_jChkCappuccinoActionPerformed

    private void jtxtIcedLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIcedLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIcedLattleActionPerformed

    private void jtxtEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEspressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEspressoActionPerformed

    private void jChkIcedCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIcedCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkIcedCappuccinoActionPerformed

    private void jtxtCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCappuccinoActionPerformed

    private void jtxtIcedCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIcedCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIcedCappuccinoActionPerformed

    private void jtxtRedVelvetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRedVelvetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRedVelvetActionPerformed

    private void jtxtCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCoffeeActionPerformed

    private void jtxtCarltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCarltonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCarltonActionPerformed

    private void jtxtQueensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQueensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQueensActionPerformed

    private void jlblSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblSubTotalActionPerformed

    private void jlblTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTotalActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        drink[0] = Double.parseDouble(jtxtLattle.getText());
        drink[1] = Double.parseDouble(jtxtIcedLattle.getText());
        drink[2] = Double.parseDouble(jtxtEspresso.getText());
        drink[3] = Double.parseDouble(jtxtCappuccino.getText());
        drink[4] = Double.parseDouble(jtxtIcedCappuccino.getText());
        
        cake[0] = Double.parseDouble(jtxtCoffee.getText());
        cake[1] = Double.parseDouble(jtxtRedVelvet.getText());
        cake[2] = Double.parseDouble(jtxtBoston.getText());
        cake[3] = Double.parseDouble(jtxtBlack.getText());
        cake[4] = Double.parseDouble(jtxtLagos.getText());
        cake[5] = Double.parseDouble(jtxtKilburn.getText());
        cake[6] = Double.parseDouble(jtxtCarlton.getText());
        cake[7] = Double.parseDouble(jtxtQueens.getText());
        
        cost[0] = jlblTax.getText();
        cost[1] = jlblSubTotal.getText();
        cost[2] = jlblTotal.getText();
        
        int refs = 1325 + (int) (Math.random() * 4238);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
        
        jtxtReceipt.append(
                "\t\t\nHasan's Cafe IUB\n"+
                "Reference Number:\t\t\t\t" + refs +
                "\n==============================================="+
                "\nLattle:\t\t\t\t\t" + drink[0] + 
                "\nIced Lattle:\t\t\t\t"+drink[1]+
                "\nEspresso:\t\t\t\t"+drink[2]+
                "\nCappuccino:\t\t\t\t"+drink[3]+
                "\nIced Cappuccino:\t\t\t\t"+drink[4]+
                "\n==============================================="+
                "\nCoffee Cake:\t\t\t\t"+cake[0]+
                "\nRed Velvet Cakes:\t\t\t\t"+cake[1]+
                "\nBoston Cream Pie:\t\t\t\t"+cake[2]+
                "\nBlack Forest Cake:\t\t\t"+cake[3]+
                "\nLagos Chocolate Cake:\t\t\t"+cake[4]+
                "\nKilburn Chocolate Cake:\t\t\t"+cake[5]+
                "\nCarlton Hill Chocolate Cake:\t\t"+cake[6]+
                "\nQueen's Park Chocolate Cake:\t\t"+cake[7]+
                "\n==============================================="+
                "\nTax:\t\t\t\t\t" + cost[0] +
                "\nSub Total:\t\t\t\t" + cost[1] +
                "\nTotal:\t\t\t\t\t" + cost[2] +
                "\n==============================================="+
                "\n\nDate: " +Tdate.format(timer.getTime()) +
                "\tTime: " +tTime.format(timer.getTime()) +
                "\n\n\t\tThank you.\n");
        
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jtxtKilburnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtKilburnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtKilburnActionPerformed

    private void jtxtBostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBostonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBostonActionPerformed

    private void jtxtLagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLagosActionPerformed

    private void jtxtBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBlackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBlackActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        jlblCostCake.setText("0");
        jlblCostDrinks.setText("0");
        jlblService.setText("5");
        jlblTax.setText("0");
        jlblSubTotal.setText("0");
        jlblTotal.setText("0");
        jtxtLattle.setText("0");
        jtxtIcedLattle.setText("0");
        jtxtEspresso.setText("0");
        jtxtCappuccino.setText("0");
        jtxtIcedCappuccino.setText("0");
        jtxtBlack.setText("0");
        jtxtLagos.setText("0");
        jtxtKilburn.setText("0");
        jtxtCarlton.setText("0");
        jtxtQueens.setText("0");
        jtxtRedVelvet.setText("0");
        jtxtBoston.setText("0");
        jtxtCoffee.setText("0");
        jtxtReceipt.setText(null);
        
        jChkLattle.setSelected(false);
        jChkIcedLattle.setSelected(false);
        jChkEspresso.setSelected(false);
        jChkCappuccino.setSelected(false);
        jChkIcedCappuccino.setSelected(false);
        jChkBlack.setSelected(false);
        jChkLagos.setSelected(false);
        jChkKilburn.setSelected(false);
        jChkCarlton.setSelected(false);
        jChkQueens.setSelected(false);
        jChkRedVelvet.setSelected(false);
        jChkBoston.setSelected(false);
        jChkCoffeeCake.setSelected(false);

    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jChkLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLattleActionPerformed

    }//GEN-LAST:event_jChkLattleActionPerformed

    private void jChkCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCappuccinoMouseClicked
        double cCap = Double.parseDouble(jlblCostDrinks.getText());
        double Cappuccino = Double.parseDouble(jtxtCappuccino.getText());
        double iCappuccino = 40;
        
        if (jChkCappuccino.isSelected())
        {
            i[0] = (Cappuccino * iCappuccino) + cCap;
            String pDrink = String.format("%.2f", i[0]);
            jlblCostDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkCappuccinoMouseClicked

    private void jChkLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLattleMouseClicked
        double cLattle = Double.parseDouble(jlblCostDrinks.getText());
        double Lattle = Double.parseDouble(jtxtLattle.getText());
        double iLattle = 35;
        
        if (jChkLattle.isSelected())
        {
            i[1] = (Lattle * iLattle) + cLattle;
            String pDrink = String.format("%.2f", i[1]);
            jlblCostDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkLattleMouseClicked

    private void jChkIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedLattleMouseClicked
        double cIcedLattle = Double.parseDouble(jlblCostDrinks.getText());
        double IcedLattle = Double.parseDouble(jtxtIcedLattle.getText());
        double iIcedLattle = 40;
        
        if (jChkIcedLattle.isSelected())
        {
            i[2] = (IcedLattle * iIcedLattle) + cIcedLattle;
            String pDrink = String.format("%.2f", i[2]);
            jlblCostDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkIcedLattleMouseClicked

    private void jChkEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkEspressoMouseClicked
        double cEspresso = Double.parseDouble(jlblCostDrinks.getText());
        double Espresso = Double.parseDouble(jtxtIcedLattle.getText());
        double iEspresso = 30;
        
        if (jChkEspresso.isSelected())
        {
            i[3] = (Espresso * iEspresso) + cEspresso;
            String pDrink = String.format("%.2f", i[3]);
            jlblCostDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkEspressoMouseClicked

    private void jChkIcedCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedCappuccinoMouseClicked
        double cIcedCap = Double.parseDouble(jlblCostDrinks.getText());
        double IcedCappuccino = Double.parseDouble(jtxtIcedCappuccino.getText());
        double iIcedCappuccino = 45;
        
        if (jChkIcedCappuccino.isSelected())
        {
            i[4] = (IcedCappuccino * iIcedCappuccino) + cIcedCap;
            String pDrink = String.format("%.2f", i[4]);
            jlblCostDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkIcedCappuccinoMouseClicked

    private void jChkCoffeeCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCoffeeCakeMouseClicked
        double cCoffeeCake = Double.parseDouble(jlblCostCake.getText());
        double CoffeeCake = Double.parseDouble(jtxtCoffee.getText());
        double iCoffeeCake = 35;
        
        if (jChkCoffeeCake.isSelected())
        {
            i[5] = (CoffeeCake * iCoffeeCake) + cCoffeeCake;
            String pCoffeeCake = String.format("%.2f", i[5]);
            jlblCostCake.setText(pCoffeeCake);
        }
    }//GEN-LAST:event_jChkCoffeeCakeMouseClicked

    private void jChkRedVelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkRedVelvetMouseClicked
        double cRedVelvet = Double.parseDouble(jlblCostCake.getText());
        double RedVelvet = Double.parseDouble(jtxtRedVelvet.getText());
        double iRedVelvet = 25;
        
        if (jChkRedVelvet.isSelected())
        {
            i[6] = (RedVelvet * iRedVelvet) + cRedVelvet;
            String pCoffeeCake = String.format("%.2f", i[6]);
            jlblCostCake.setText(pCoffeeCake);
        }
    }//GEN-LAST:event_jChkRedVelvetMouseClicked

    private void jChkBostonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBostonMouseClicked
        double cBoston = Double.parseDouble(jlblCostCake.getText());
        double Boston = Double.parseDouble(jtxtBoston.getText());
        double iBoston = 37;
        
        if (jChkBoston.isSelected())
        {
            i[7] = (Boston * iBoston) + cBoston;
            String pCoffeeCake = String.format("%.2f", i[7]);
            jlblCostCake.setText(pCoffeeCake);
        }
    }//GEN-LAST:event_jChkBostonMouseClicked

    private void jChkBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBlackMouseClicked
        double cBlack = Double.parseDouble(jlblCostCake.getText());
        double Black = Double.parseDouble(jtxtBlack.getText());
        double iBlack = 33;
        
        if (jChkBlack.isSelected())
        {
            i[8] = (Black * iBlack) + cBlack;
            String pCoffeeCake = String.format("%.2f", i[8]);
            jlblCostCake.setText(pCoffeeCake);
        }
    }//GEN-LAST:event_jChkBlackMouseClicked

    private void jChkLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLagosMouseClicked
        double cLagos = Double.parseDouble(jlblCostCake.getText());
        double Lagos = Double.parseDouble(jtxtLagos.getText());
        double iLagos = 50;
        
        if (jChkLagos.isSelected())
        {
            i[9] = (Lagos * iLagos) + cLagos;
            String pCoffeeCake = String.format("%.2f", i[9]);
            jlblCostCake.setText(pCoffeeCake);
        }
    }//GEN-LAST:event_jChkLagosMouseClicked

    private void jChkKilburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkKilburnMouseClicked
        double cKilburn = Double.parseDouble(jlblCostCake.getText());
        double Kilburn = Double.parseDouble(jtxtKilburn.getText());
        double iKilburn = 35;
        
        if (jChkKilburn.isSelected())
        {
            i[10] = (Kilburn * iKilburn) + cKilburn;
            String pCoffeeCake = String.format("%.2f", i[10]);
            jlblCostCake.setText(pCoffeeCake);
        }
    }//GEN-LAST:event_jChkKilburnMouseClicked

    private void jChkCarltonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCarltonMouseClicked
        double cCarlton = Double.parseDouble(jlblCostCake.getText());
        double Carlton = Double.parseDouble(jtxtCarlton.getText());
        double iCarlton = 45;
        
        if (jChkCarlton.isSelected())
        {
            i[11] = (Carlton * iCarlton) + cCarlton;
            String pCoffeeCake = String.format("%.2f", i[11]);
            jlblCostCake.setText(pCoffeeCake);
        }
    }//GEN-LAST:event_jChkCarltonMouseClicked

    private void jChkQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkQueensMouseClicked
        double cQueens = Double.parseDouble(jlblCostCake.getText());
        double Queens = Double.parseDouble(jtxtQueens.getText());
        double iQueens = 50;
        
        if (jChkQueens.isSelected())
        {
            i[12] = (Queens * iQueens) + cQueens;
            String pCoffeeCake = String.format("%.2f", i[12]);
            jlblCostCake.setText(pCoffeeCake);
        }
    }//GEN-LAST:event_jChkQueensMouseClicked

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        drink[0] = Double.parseDouble(jlblCostDrinks.getText());
        drink[1] = Double.parseDouble(jlblCostCake.getText());
        drink[2] = Double.parseDouble(jlblService.getText());
        
        double cTotall = (drink[0] + drink[1] + drink[2]);
        
        String iTaxTotal = String.format("৳ %.2f", cTotall / 100);
        jlblTax.setText(iTaxTotal);
        
        double subTotal = (cTotall);
        String isubTotal = String.format("৳ %.2f", subTotal);
        jlblSubTotal.setText(isubTotal);
        
        double allTotal = (cTotall);
        String iTotal = String.format("৳ %.2f", allTotal + (allTotal / 100));
        jlblTotal.setText(iTotal);
        
        String CostD = String.format("৳ %.2f", drink[0]);
        jlblCostDrinks.setText(CostD);
        
        String CostC = String.format("৳ %.2f", drink[1]);
        jlblCostCake.setText(CostC);
        
        String Service = String.format("৳ %.2f", drink[2]);
        jlblService.setText(Service);
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jtxtLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLattleMouseClicked
        jtxtLattle.setText(null);
    }//GEN-LAST:event_jtxtLattleMouseClicked

    private void jtxtIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIcedLattleMouseClicked
        jtxtIcedLattle.setText(null);
    }//GEN-LAST:event_jtxtIcedLattleMouseClicked

    private void jtxtEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEspressoMouseClicked
        jtxtEspresso.setText(null);
    }//GEN-LAST:event_jtxtEspressoMouseClicked

    private void jtxtCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCappuccinoMouseClicked
        jtxtCappuccino.setText(null);
    }//GEN-LAST:event_jtxtCappuccinoMouseClicked

    private void jtxtIcedCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIcedCappuccinoMouseClicked
        jtxtIcedCappuccino.setText(null);
    }//GEN-LAST:event_jtxtIcedCappuccinoMouseClicked

    private void jtxtCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCoffeeMouseClicked
        jtxtCoffee.setText(null);
    }//GEN-LAST:event_jtxtCoffeeMouseClicked

    private void jtxtRedVelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtRedVelvetMouseClicked
        jtxtRedVelvet.setText(null);
    }//GEN-LAST:event_jtxtRedVelvetMouseClicked

    private void jtxtBostonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBostonMouseClicked
        jtxtBoston.setText(null);
    }//GEN-LAST:event_jtxtBostonMouseClicked

    private void jtxtBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBlackMouseClicked
        jtxtBlack.setText(null);
    }//GEN-LAST:event_jtxtBlackMouseClicked

    private void jtxtLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLagosMouseClicked
        jtxtLagos.setText(null);
    }//GEN-LAST:event_jtxtLagosMouseClicked

    private void jtxtKilburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKilburnMouseClicked
        jtxtKilburn.setText(null);
    }//GEN-LAST:event_jtxtKilburnMouseClicked

    private void jtxtCarltonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCarltonMouseClicked
        jtxtCarlton.setText(null);
    }//GEN-LAST:event_jtxtCarltonMouseClicked

    private void jtxtQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtQueensMouseClicked
        jtxtQueens.setText(null);
    }//GEN-LAST:event_jtxtQueensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JCheckBox jChkBlack;
    private javax.swing.JCheckBox jChkBoston;
    private javax.swing.JCheckBox jChkCappuccino;
    private javax.swing.JCheckBox jChkCarlton;
    private javax.swing.JCheckBox jChkCoffeeCake;
    private javax.swing.JCheckBox jChkEspresso;
    private javax.swing.JCheckBox jChkIcedCappuccino;
    private javax.swing.JCheckBox jChkIcedLattle;
    private javax.swing.JCheckBox jChkKilburn;
    private javax.swing.JCheckBox jChkLagos;
    private javax.swing.JCheckBox jChkLattle;
    private javax.swing.JCheckBox jChkQueens;
    private javax.swing.JCheckBox jChkRedVelvet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jlblCostCake;
    private javax.swing.JTextField jlblCostDrinks;
    private javax.swing.JTextField jlblService;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTax;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jtxtBlack;
    private javax.swing.JTextField jtxtBoston;
    private javax.swing.JTextField jtxtCappuccino;
    private javax.swing.JTextField jtxtCarlton;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtEspresso;
    private javax.swing.JTextField jtxtIcedCappuccino;
    private javax.swing.JTextField jtxtIcedLattle;
    private javax.swing.JTextField jtxtKilburn;
    private javax.swing.JTextField jtxtLagos;
    private javax.swing.JTextField jtxtLattle;
    private javax.swing.JTextField jtxtQueens;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtRedVelvet;
    // End of variables declaration//GEN-END:variables
}
